//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiquetes_prof
    {
        public int Codigo_tiquete { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Usuario { get; set; }
        public string Prioridad { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Asignado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
